base_model = "alibaba/qwen3.5-35b-a3b"
name = "Qwen3.5 35B A3B"

[cost]
input = 0.14
output = 1
cache_read = 0.05
cache_write = 0

[limit]
output = 262_144

[modalities]
input = ["text", "image", "video"]
