name = "gpt-oss-20b"
family = "gpt-oss"
release_date = "2025-08-05"
last_updated = "2025-08-05"
attachment = false
reasoning = true
temperature = true
tool_call = true
structured_output = true
open_weights = true

[cost]
input = 0.029
output = 0.14
cache_read = 0
cache_write = 0

[limit]
context = 131_072
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
